version: '3'

services:
  database:
    container_name: rental_db
    image: 'postgres:14-alpine'
    ports:
      - "8081:5432"
    environment:
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: public
    volumes:
      - ./postgresdb/:/var/lib/postgresql/data/